lets know the difference between the loc and iloc ## indexers

In [1]:
import pandas as pd

df = pd.read_csv(r"D:\sql_ultimate\sql-ultimate-course-main\datasets\OrdersArchive.csv",encoding='utf-8')

df

,OrderID,ProductID,CustomerID,SalesPersonID,OrderDate,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
0,1,101,2,3,2024-04-01,2024-04-05,Shipped,123 Main St,456 Billing St,1,10,2024-04-01 12:34:56.0000000
1,2,102,3,3,2024-04-05,2024-04-10,Shipped,456 Elm St,789 Billing St,1,15,2024-04-05 23:22:04.0000000
2,3,101,1,4,2024-04-10,2024-04-25,Shipped,789 Maple St,789 Maple St,2,20,2024-04-10 18:24:08.0000000
3,4,105,1,3,2024-04-20,2024-04-25,Shipped,987 Victory Lane,NaN,2,60,2024-04-20 05:50:33.0000000
4,4,105,1,3,2024-04-20,2024-04-25,Delivered,987 Victory Lane,NaN,2,60,2024-04-20 14:50:33.0000000
5,5,104,2,5,2024-05-01,2024-05-05,Shipped,345 Oak St,678 Pine St,1,25,2024-05-01 14:02:41.0000000
6,6,104,3,5,2024-05-05,2024-05-10,Delivered,543 Belmont Rd.,NaN,2,50,2024-05-06 15:34:57.0000000
7,6,104,3,5,2024-05-05,2024-05-10,Delivered,543 Belmont Rd.,3768 Door Way,2,50,2024-05-07 13:22:05.0000000
8,6,101,3,5,2024-05-05,2024-05-10,Delivered,543 Belmont Rd.,3768 Door Way,2,50,2024-05-12 20:36:55.0000000
9,7,102,3,5,2024-06-15,2024-06-20,Shipped,111 Main St,222 Billing St,0,60,2024-06-16 23:25:15.0000000

In [15]:
# print row 5 
# the loc function works on labels the number of row is like a name of row it can a string also

# print(df.loc[0])
# just print sales 
# print(df.loc[0,'Sales']) # the row and the column name
# print(df.loc['Sales'])

In [10]:
# ## iloc  it is also return a row but it works on positions

# # df.iloc[7]
# df.iloc['Sales']# only index position
## want to check row 6's order_status
# for iloc function give the column positon number
df.iloc[6,6]

'Delivered'

In [14]:
# check head
# df.head(5)# top 5
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        10 non-null     int64
 1   ProductID      10 non-null     int64
 2   CustomerID     10 non-null     int64
 3   SalesPersonID  10 non-null     int64
 4   OrderDate      10 non-null     str
 5   ShipDate       10 non-null     str
 6   OrderStatus    10 non-null     str
 7   ShipAddress    10 non-null     str
 8   BillAddress    7 non-null      str
 9   Quantity       10 non-null     int64
 10  Sales          10 non-null     int64
 11  CreationTime   10 non-null     str
dtypes: int64(6), str(6)
memory usage: 1.1 KB

In [16]:
df['Sales']

0    10
1    15
2    20
3    60
4    60
5    25
6    50
7    50
8    50
9    60
Name: Sales, dtype: int64

In [ ]:
# access whole col throiugh loc
df.loc[:,'Sales',]

0    10
1    15
2    20
3    60
4    60
5    25
6    50
7    50
8    50
9    60
Name: Sales, dtype: int64

In [19]:
df[['Sales','CustomerID']]

   Sales  CustomerID
0     10           2
1     15           3
2     20           1
3     60           1
4     60           1
5     25           2
6     50           3
7     50           3
8     50           3
9     60           3

In [23]:
df.loc[6, ['Sales',"CustomerID"]]

Sales         50
CustomerID     3
Name: 6, dtype: int64