In [1]:
import pandas as pd

data_f1=pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex1.csv")
data_f2 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex2.csv")

data_f3 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex3.csv")
data_f4 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex4.csv",encoding='utf-8')

In [2]:
data_f1.head()

,Item Code,Item Name,Category Code,Category Name
0,102900005115168,Niushou Shengcai,1011010101,Flower/Leaf Vegetables
1,102900005115199,Sichuan Red Cedar,1011010101,Flower/Leaf Vegetables
2,102900005115625,Local Xiaomao Cabbage,1011010101,Flower/Leaf Vegetables
3,102900005115748,White Caitai,1011010101,Flower/Leaf Vegetables
4,102900005115762,Amaranth,1011010101,Flower/Leaf Vegetables

In [10]:
data_f3.head()
# data_f3.info()

         Date        Item Code  Wholesale Price (RMB/kg)
0  2020-07-01  102900005115762                      3.88
1  2020-07-01  102900005115779                      6.72
2  2020-07-01  102900005115786                      3.19
3  2020-07-01  102900005115793                      9.24
4  2020-07-01  102900005115823                      7.03

In [4]:
data_f4.head()

         Item Code                 Item Name  Loss Rate (%)
0  102900005115168          Niushou Shengcai           4.39
1  102900005115199         Sichuan Red Cedar          10.46
2  102900005115250  Xixia Black Mushroom (1)          10.80
3  102900005115625     Local Xiaomao Cabbage           0.18
4  102900005115748              White Caitai           8.78

In [9]:
data_f2.head()
data_f2.info()
data_f2.shape
data_f3.shape

<class 'pandas.DataFrame'>
RangeIndex: 878503 entries, 0 to 878502
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Date                         878503 non-null  str
 1   Time                         878503 non-null  str
 2   Item Code                    878503 non-null  int64
 3   Quantity Sold (kilo)         878503 non-null  float64
 4   Unit Selling Price (RMB/kg)  878503 non-null  float64
 5   Sale or Return               878503 non-null  str
 6   Discount (Yes/No)            878503 non-null  str
dtypes: float64(2), int64(1), str(4)
memory usage: 46.9 MB

(55982, 3)