the problem is that find the high cell day and good rating day of super market

In [16]:
# important libs to use
import pandas as pd
import matplotlib.pyplot as pt
import datetime as dt
import seaborn as sb

In [2]:
# load data 
data_f1=pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex1.csv")
data_f2 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex2.csv")

data_f3 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex3.csv")
data_f4 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex4.csv",encoding='utf-8')

In [30]:
data_f2.info()

# data_f2.info()

<class 'pandas.DataFrame'>
RangeIndex: 878503 entries, 0 to 878502
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Date                         878503 non-null  datetime64[us]
 1   Time                         878503 non-null  str
 2   Item Code                    878503 non-null  int64
 3   Quantity Sold (kilo)         878503 non-null  float64
 4   Unit Selling Price (RMB/kg)  878503 non-null  float64
 5   Sale or Return               878503 non-null  str
 6   Discount (Yes/No)            878503 non-null  str
 7   Day_of_week                  878503 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 53.6 MB

In [4]:
data_f2.head(4)

,Date,Time,Item Code,Quantity Sold (kilo),Unit Selling Price (RMB/kg),Sale or Return,Discount (Yes/No)
0,2020-07-01,09:15:07.924,102900005117056,0.396,7.6,sale,No
1,2020-07-01,09:17:27.295,102900005115960,0.849,3.2,sale,No
2,2020-07-01,09:17:33.905,102900005117056,0.409,7.6,sale,No
3,2020-07-01,09:19:45.450,102900005115823,0.421,10.0,sale,No

In [9]:
# step 1 datetime tracking change the txt formet date time data into actual datetime type
data_f2['Date'] = pd.to_datetime(data_f2["Date"])

In [32]:
# confirm it
# data_f2.info()
data_f2['Date'].head()

0   2020-07-01
1   2020-07-01
2   2020-07-01
3   2020-07-01
4   2020-07-01
Name: Date, dtype: datetime64[us]

In [17]:
# add a new column with days name
data_f2['Day_of_week']=  data_f2['Date'].dt.day_name() # type: ignore

In [19]:
data_f2.tail(4)

,Date,Time,Item Code,Quantity Sold (kilo),Unit Selling Price (RMB/kg),Sale or Return,Discount (Yes/No),Day_of_week
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,sale,No,Friday
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,sale,No,Friday
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,sale,No,Friday
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,sale,No,Friday

In [ ]:
# aggregation find the average of total sales accordng to days
# data_f2.groupby(['Day_of_week'])['']

In [33]:
# merge the data 
extract_from_df3= data_f3[['Item Code','Wholesale Price (RMB/kg)']]
extract_from_df3.head()
extract_from_df2 = data_f2[['Item Code','Day_of_week','Date']]

In [ ]:
# merge it with df2
new_data = pd.merge(extract_from_df2 , extract_from_df3, on='Item Code') ????

MemoryError: Unable to allocate 4.50 GiB for an array with shape (603915514,) and data type int64