In [ ]:
# import and clean a large data set
import pandas as pd

large_data_set= pd.read_csv(r"C:\Users\fatima28\Downloads\archive\college_students_habits_1M.csv", encoding='utf-8')

64.85610525538743

In [18]:
# check high of score and min and mean
print(large_data_set['final_score'].mean())
print(large_data_set['final_score'].max())
print(large_data_set['final_score'].min())

64.85610525538743
100.0
0.0

In [2]:
# check the total rows and columns ,datatypes and NAN values
large_data_set.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 42 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   study_hours               1000000 non-null  float64
 1   attendance                1000000 non-null  float64
 2   assignment_completion     1000000 non-null  float64
 3   midterm_score             1000000 non-null  float64
 4   final_score               1000000 non-null  float64
 5   project_score             1000000 non-null  float64
 6   backlogs                  1000000 non-null  int64
 7   sleep_hours               1000000 non-null  float64
 8   stress                    1000000 non-null  float64
 9   anxiety                   1000000 non-null  float64
 10  depression                1000000 non-null  float64
 11  motivation                1000000 non-null  float64
 12  concentration             1000000 non-null  float64
 13  time_management           1000000 non-null  float64
 14  self_discipline           1000000 non-null  float64
 15  social_media_hours        1000000 non-null  float64
 16  gaming_hours              1000000 non-null  float64
 17  netflix_hours             1000000 non-null  float64
 18  screen_time               1000000 non-null  float64
 19  physical_activity         1000000 non-null  float64
 20  junk_food_frequency       1000000 non-null  float64
 21  caffeine_mg               1000000 non-null  float64
 22  late_night_frequency      1000000 non-null  float64
 23  procrastination_score     1000000 non-null  float64
 24  family_income             1000000 non-null  float64
 25  parental_education_level  1000000 non-null  int64
 26  internet_quality          1000000 non-null  float64
 27  library_visits            1000000 non-null  float64
 28  online_courses_completed  1000000 non-null  int64
 29  part_time_hours           1000000 non-null  float64
 30  peer_study_group          1000000 non-null  int64
 31  relationship_status       1000000 non-null  int64
 32  hostel_student            1000000 non-null  int64
 33  extracurricular_hours     1000000 non-null  float64
 34  phone_unlocks_per_day     1000000 non-null  float64
 35  previous_gpa              1000000 non-null  float64
 36  class_participation       1000000 non-null  float64
 37  weekly_study_sessions     1000000 non-null  float64
 38  group_study_hours         1000000 non-null  float64
 39  financial_stress          1000000 non-null  float64
 40  gpa                       1000000 non-null  float64
 41  performance_level         998442 non-null   str
dtypes: float64(35), int64(6), str(1)
memory usage: 320.4 MB

In [ ]:
large_data_set.loc[:,'performance_level'].tail(200)

In [3]:
# check null values 
null_val=large_data_set["performance_level"].isna()
print(type(null_val))
# print(null_val)
large_data_set.loc[null_val,['performance_level','stress']]

<class 'pandas.Series'>

       performance_level    stress
108                  NaN  6.049912
856                  NaN  3.410254
875                  NaN  6.066334
1031                 NaN  5.412525
1437                 NaN  6.235285
...                  ...       ...
996116               NaN  8.186305
997049               NaN  3.973548
997440               NaN  5.862792
997673               NaN  6.726327
997819               NaN  4.784115

[1558 rows x 2 columns]

In [7]:
# check attendecnce > 75%
high_attendence = large_data_set['attendance']>=75# boolean masking
# total_attendence
print(type(high_attendence))
# print(total_attendence)
large_data_set.loc[high_attendence ,['attendance','final_score']]

<class 'pandas.Series'>

        attendance  final_score
6        82.386530    71.327520
7       100.000000    90.172585
10       78.555680    76.216354
12       87.266914    77.344090
17       78.776130    68.554886
...            ...          ...
999986   81.196380    67.673460
999989   79.104610    59.898945
999990   79.751540    74.084050
999991   77.384740    71.225430
999995   78.020386    59.887230

[500794 rows x 2 columns]

In [ ]:
lower_atten = large_data_set['attendance']<75

large_data_set.loc[lower_atten,['attendance','final_score']]

In [ ]:
# check the mean

print(lower_atten.mean())
print(high_attendence.mean())
if lower_atten.mean() < high_attendence.mean():
    
    print('attendance affect on final score')
else:
    print('bias')

0.499206
0.500794
attendance affect on final score

In [23]:
if large_data_set.loc[lower_atten,'final_score'].mean() > 64.85610525538743:
    print('attandace not affect on final score')
    print(large_data_set.loc[lower_atten,'final_score'].mean() )
else:
    print('lower attendance  affect on final score')
    print(large_data_set.loc[lower_atten,'final_score'].mean())

lower attendance  affect on final score
51.41721007168272