In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv(r'C:\Users\FatimaArain\Downloads\archive\retail_data\order_details.csv')

In [5]:
# check the data and find what can be done with thia data
df.head()

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
1,ORD00002,PRDCT0028,2,4.17,5.31,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
3,ORD00003,PRDCT0030,2,0.90,1.35,0.00,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30271 entries, 0 to 30270
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       30271 non-null  str
 1   ProductID     30271 non-null  str
 2   Quantity      30271 non-null  int64
 3   UnitCost      30271 non-null  float64
 4   UnitPrice     30271 non-null  float64
 5   DiscountRate  30271 non-null  float64
 6   IsReturned    30271 non-null  int64
 7   ReturnDate    30271 non-null  str
 8   ReturnTime    30271 non-null  str
 9   ReturnReason  1424 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 3.3 MB

In [4]:
# extract categorial data
df['IsReturned'].unique()
cat = df.loc[:,['IsReturned']]

In [5]:
# varify
cat.shape
cat.dtypes
cat['IsReturned'].dtype

dtype('int64')

In [6]:
type(cat['IsReturned'])

pandas.Series

In [7]:
# exttact productID,qunatity and unit price
a=['ProductID','Quantity','UnitPrice']
cat['ProductID']= df['ProductID']
cat['Quantity']= df['Quantity']
cat['UnitPrice']=df['UnitPrice']

In [8]:
cat

       IsReturned  ProductID  Quantity  UnitPrice
0               0  PRDCT0056         3       3.38
1               0  PRDCT0028         2       5.31
2               0  PRDCT0001        13      25.77
3               0  PRDCT0030         2       1.35
4               0  PRDCT0003         3      20.35
...           ...        ...       ...        ...
30266           0  PRDCT0049         2       5.44
30267           0  PRDCT0052         3       4.71
30268           0  PRDCT0033         3       4.06
30269           0  PRDCT0030         1       1.64
30270           0  PRDCT0018         1      11.66

[30271 rows x 4 columns]

In [9]:
# extraction
print(df.iloc[1])
print(df.iloc[5])
print(df.iloc[-1])

OrderID           ORD00002
ProductID        PRDCT0028
Quantity                 2
UnitCost              4.17
UnitPrice             5.31
DiscountRate           0.0
IsReturned               0
ReturnDate      9999-12-31
ReturnTime        00:00:00
ReturnReason           NaN
Name: 1, dtype: object
OrderID           ORD00004
ProductID        PRDCT0017
Quantity                 5
UnitCost              2.84
UnitPrice              3.6
DiscountRate           0.0
IsReturned               0
ReturnDate      9999-12-31
ReturnTime        00:00:00
ReturnReason           NaN
Name: 5, dtype: object
OrderID           ORD10000
ProductID        PRDCT0018
Quantity                 1
UnitCost              8.88
UnitPrice            11.66
DiscountRate          0.05
IsReturned               0
ReturnDate      9999-12-31
ReturnTime        00:00:00
ReturnReason           NaN
Name: 30270, dtype: object

In [10]:
# filter
avg = df['Quantity'].mean()
temp = df[df['Quantity'] > avg]

In [35]:
temp

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN
5,ORD00004,PRDCT0017,5,2.84,3.60,0.00,0,9999-12-31,00:00:00,NaN
6,ORD00004,PRDCT0021,4,1.65,2.36,0.00,0,9999-12-31,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...
30257,ORD09995,PRDCT0012,11,3.63,5.39,0.10,0,9999-12-31,00:00:00,NaN
30258,ORD09995,PRDCT0006,5,11.10,13.99,0.00,0,9999-12-31,00:00:00,NaN
30261,ORD09998,PRDCT0023,3,2.71,3.69,0.00,0,9999-12-31,00:00:00,NaN
30267,ORD09999,PRDCT0052,3,3.30,4.71,0.00,0,9999-12-31,00:00:00,NaN
30268,ORD09999,PRDCT0033,3,2.87,4.06,0.00,0,9999-12-31,00:00:00,NaN

In [16]:
avg

np.float64(2.681312146939315)

In [13]:
# use of and multi conditions 
return_rate=df['IsReturned'].mean()
# check the avg purchase qunatiy and avg is returned qunatiy greater then 
b = df[(df['IsReturned']> return_rate )& (df['Quantity']> avg)]

In [15]:
b.loc[:,['ProductID','IsReturned','Quantity']]

       ProductID  IsReturned  Quantity
35     PRDCT0029           1        18
61     PRDCT0016           1         3
88     PRDCT0001           1         4
89     PRDCT0027           1         3
140    PRDCT0025           1         8
...          ...         ...       ...
30091  PRDCT0069           1         4
30140  PRDCT0085           1         4
30166  PRDCT0028           1         3
30229  PRDCT0090           1         3
30242  PRDCT0062           1         4

[476 rows x 3 columns]

In [ ]:
# problem 7
# | 
# check the product id is quantity is greater then avg or is returner
re = df['Quantity'].mean()
r
df.loc[(df['Quantity'] > re) | (df['IsReturned']==1)]

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN
5,ORD00004,PRDCT0017,5,2.84,3.60,0.00,0,9999-12-31,00:00:00,NaN
6,ORD00004,PRDCT0021,4,1.65,2.36,0.00,0,9999-12-31,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...
30257,ORD09995,PRDCT0012,11,3.63,5.39,0.10,0,9999-12-31,00:00:00,NaN
30258,ORD09995,PRDCT0006,5,11.10,13.99,0.00,0,9999-12-31,00:00:00,NaN
30261,ORD09998,PRDCT0023,3,2.71,3.69,0.00,0,9999-12-31,00:00:00,NaN
30267,ORD09999,PRDCT0052,3,3.30,4.71,0.00,0,9999-12-31,00:00:00,NaN
30268,ORD09999,PRDCT0033,3,2.87,4.06,0.00,0,9999-12-31,00:00:00,NaN